theme: jekyll-theme-minimal
logo: img/ubirch-logo-single.png
title: Developer Pages
subtitle: Documentation and Tutorials
# description: A collection of concepts, documentation and tutorials to make your ESG data trustworthy by using the Ubirch Turst Protocol.
description: Collect, Seal and Verify ESG data with ease
show_downloads: false
highlighter: rouge
