theme: jekyll-theme-minimal
logo: img/ubirch-logo-single.png
title: Developer Pages
subtitle: Building Trust for the Internet of Things by Leveraging Blockchain.
# description: A collection of concepts, documentation and tutorials to make your IoT device data trustworthy by using the Ubirch Turst Protocol.
#description:
show_downloads: false
highlighter: rouge
