theme: jekyll-theme-minimal
logo: img/ubirch-logo.png
title: Documentation
subtitle: The Blockchain for Things.
description: A collection of concepts, documentation and tutorials to make your IoT device data trustworthy.
show_downloads: false
highlighter: rouge
